###
GET http://localhost:8000/pets

###
POST http://localhost:8000/pets
Content-Type: application/json

{
    "age": 7,
    "kind": "rainbow",
    "name": "test"
  }

###
PUT http://localhost:8000/pets/2
Content-Type: application/json

{
    "age": 7,
    "kind": "this changed",
    "name": "test"
  }

###
DELETE http://localhost:8000/pets/3
