###
GET http://localhost:8000/pets

###
POST http://localhost:8000/pets
Content-Type: application/json

{
    "age": 7,
    "kind": "rainbow",
    "name": "bozo"
  }

###
PUT http://localhost:8000/pets/2
Content-Type: application/json

 {
    "age": 15,
    "kind": "baboon",
    "name": "bozo"
  } 

###
DELETE http://localhost:8000/pets/2
